### ISSUE TITLE
Polar plugin uses hardcoded deviceId’s to establish the connection to the device

### ISSUE THREAD

**Issue by fschulting** [RADAR-base/radar-commons-android#450]
The polar plugin uses the specific api.connectToDevice(deviceId) function from the Polar SDK to automatically connect to the device of which the deviceId is hardcoded in the plugin.

This deviceId can be changed in PolarManager.

[This PR for Polar-autoscan ](https://github.com/RADAR-base/radar-commons-android/pull/451) does not use a hardcoded deviceId, but the api.autoConnectToDevice() function from the Polar SDK to automatically connect to a compatible Polar device. 
Although this might be the preferred method, this connection could not always be established for the ‘Polar Vantage V3’ and ‘Polar Sense’ devices.

A solution would be to either resolve the issues with the autoscan function, or to add a pop-up in the pRMT app in which the user can manually add the deviceId, to which a connection could be established (as in the current Polar plugin).

**Comment by yatharthranjan** [comment]
closed by #461
